const LOTTERY_DAY = 'YYYYMMDD';
const LOTTERY_TYPE = {
  SIMPLE: 0,
  ONE_BIT: 10,
  TWO_BIT: 20,
  THREE_BIT: 30,
  FIVE_BIT: 40,
};
const LOTTERY_LIMIT = 10;
const LOTTERY_TIME = 600000;
export {LOTTERY_DAY, LOTTERY_TYPE, LOTTERY_TIME, LOTTERY_LIMIT};
